### ISSUE TITLE
Handle websocket disconnect

### ISSUE THREAD

**Issue by m4eba** [m4eba/twitch-dump#2]

**Comment by m4eba** [comment]
console error output
```
ws disconnected, reconnect in 5 seconds
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN pubsub-edge.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on WebSocket instance at:
    at ClientRequest.<anonymous> (/home/pi/dump/twitch-dump/node_modules/ws/lib/websocket.js:554:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'pubsub-edge.twitch.tv'
}
```
