### ISSUE TITLE
Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by m4eba** [m4eba/twitch-dump#6]
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at WriteStream.Writable.write (_stream_writable.js:292:11)
    at Chat.writeLine (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:108:65)
    at Chat.writeData (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:100:22)
    at Chat.wsMessage (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:67:14)
    at WebSocket.<anonymous> (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:36:46)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/pi/dump/twitch-dump/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/pi/dump/twitch-dump/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/home/pi/dump/twitch-dump/node_modules/ws/lib/receiver.js:366:17)
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

```

**Comment by m4eba** [comment]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at WriteStream.Writable.write (_stream_writable.js:292:11)
    at Chat.writeLine (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:114:65)
    at Chat.writeData (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:106:22)
    at Chat.wsMessage (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:73:14)
    at WebSocket.<anonymous> (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:38:46)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/pi/dump/twitch-dump/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/pi/dump/twitch-dump/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/home/pi/dump/twitch-dump/node_modules/ws/lib/receiver.js:366:17)
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
