### ISSUE TITLE
crash - WebSocket is not open

### ISSUE THREAD

**Issue by m4eba** [m4eba/twitch-dump#7]
```
/home/pi//twitch-dump/node_modules/ws/lib/websocket.js:328
      throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');
      ^

Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/home/pi//twitch-dump/node_modules/ws/lib/websocket.js:328:13)
    at Chat.ping (/home/pi//twitch-dump/build/chat.js:12:17)
    at Timeout._onTimeout (/home/pi//twitch-dump/build/WebSocketLogger.js:54:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by m4eba** [comment]
```
events pong +175ms
ping timeout?
ws disconnected, reconnect in 5 seconds
/home/pi/dump/twitch-dump/node_modules/ws/lib/websocket.js:328
      throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');
      ^

Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/home/pi/dump/twitch-dump/node_modules/ws/lib/websocket.js:328:13)
    at Chat.ping (/home/pi/dump/twitch-dump/build/chat.js:12:17)
    at Timeout._onTimeout (/home/pi/dump/twitch-dump/build/WebSocketLogger.js:54:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
